### ISSUE TITLE
How I can increase sample rate?

### ISSUE THREAD

**Issue by leCandas** [yhur/arduplot#7]
Hello, thanks for this project it works very well with a 1-second sample rate...
I do this by adding a delay(1000) I am monitoring 10 channels and I got 10 channels plotted.
When I set delay(100) I am getting channels duplicated by 10 and the plotter starts drawing 100 channels I guess each channel 10 times.

Is it possible to change the sample rate of the plotter?

**Comment by leCandas** [comment]
I guess I am having exactly the same issue mentioned here, I am running this on Windows 11
https://github.com/yhur/arduplot/issues/4

**Comment by yhur** [comment]
Hi,
As you may know, this uses the animation library from matplotlib.

So the possible minimal plotting granularity would depend on the host computer’s performance regarding on the python and the associated libraries like the matplotlib.animation. And it would add another time constraints if you run it through PIO since the additional TCP communication layer as well as the PIO would add some more latency.
